### ISSUE TITLE
Remove vendor directory

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes-sigs/bootkube#1046]
If/when #1043 is fixed, can we remove the vendor directory requirement? `go mod vendor` is fast.

**Comment by invidian** [comment]
To be honest, I think we could keep `vendor` directory, so Docker builds are faster and you don't hit issues with outages of dependencies hosting etc.

**Comment by lingsamuel** [comment]
+1 remove vendor
Just because my IDE (JetBrains goland) supports symlinks in vendor dir no very well... It doesn't treat things in the original path and symlinked path as the same one, which makes functionalities like `find usage` only return a partial result set, really annoying when reading codes.
I have to write a script to delete all symlinks when I need to read codes and regen them when I need to compile  :joy:

**Comment by mrbobbytables** [comment]
This project is being archives, for more information see this issue:
https://github.com/kubernetes/org/issues/2824

/close
