### ISSUE TITLE
Enable api server aggrigation

### ISSUE THREAD

**Issue by rmenn** [kubernetes-sigs/bootkube#1053]
With kubernetes 1.16 bootkube fails conformance with the api-server aggregator tests

```
Summarizing 1 Failure:

[Fail] [sig-api-machinery] Aggregator [It] Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]
/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:328

Ran 276 of 4897 Specs in 6959.786 seconds
FAIL! -- 275 Passed | 1 Failed | 0 Pending | 4621 Skipped
--- FAIL: TestE2E (6959.85s)
FAIL

Ginkgo ran 1 suite in 1h56m1.162165977s
Test Suite Failed
2019/10/25 09:37:25 Saving results at /tmp/results
2019/10/25 09:37:25 running command: exit status 1
```

Since there is a requirement for conformance to pass this should be added to the `render` process. This would involve adding
* Another set of TLS Certs
* Flags in the kube-apiserver daemonset

**Comment by rmenn** [comment]
@aaronlevy @dghubble RFC, please

**Comment by dghubble** [comment]
In recent years, the hope was for this repo to focus more on the bootkube bootstrapper and checkpointer tools themselves, with less focus on templating/rendering (which can be done so many different ways based on tastes/needs beforehand). However, the render examples weren't dropped since they helped show example usage and support testing.

I'd say it'd be good to think about this as a tool, separate from the concerns of a distribution and distribution conformance with apiserver aggregation render options. In that light its not a hard blocker if that's a concern. But I'm less involved in bootkube now if others have different opinions (?)

**Comment by rmenn** [comment]
This was added in #1064 
/close
